"""Modify transactions table

Revision ID: 6d202b71f7c9
Revises: 76005cd038ad
Create Date: 2022-07-02 17:06:37.277634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d202b71f7c9'
down_revision = '76005cd038ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receiver', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'receiver')
    # ### end Alembic commands ###
